name: Docker Image CI

on:
  push:
    branches:
      - master
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "$DOCKER_PASSWORD"
        echo "$DOCKER_PASSWORD" | docker login --username gardner --password-stdin
        docker build . --file Dockerfile --tag gardner/ngrok:latest
        docker push gardner/ngrok
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
